---
- hosts: all
  sudo: true
  vars_files:
    - vars/security.yml
    - vars/firewall.yml
    - vars/nginx.yml
    - vars/php.yml
  roles:
    - security
    - firewall
    - nginx
    - php
  pre_tasks:
    - name: Add percona apt signing key
      apt_key: keyserver=keys.gnupg.net id=1C4CBDCDCD2EFD2A state=present
      when: ansible_os_family == "Debian"
    - name: Add Percona repository
      apt_repository: repo='deb http://repo.percona.com/apt trusty main' state=present
      when: ansible_os_family == "Debian"
    - name: Add Percona source repository
      apt_repository: repo='deb-src http://repo.percona.com/apt trusty main' state=present
      when: ansible_os_family == "Debian"
    - name: Update apt cache
      apt: update_cache=yes
      when: ansible_os_family == "Debian"
  post_tasks:
    - name: Ensure Percona packages are installed.
      apt: "name={{ item }} state=installed"
      with_items: 
        - python-pycurl
        - python-mysqldb
        - percona-server-server-5.5
        - percona-server-common-5.5
        - percona-server-client-5.5
      environment:
        DEBIAN_FRONTEND: noninteractive
      when: ansible_os_family == "Debian"
